"""add_candidate_resumes

Revision ID: 5dbb13e978d8
Revises: 4c841354f311
Create Date: 2026-04-25 21:00:58.018690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbb13e978d8'
down_revision: Union[str, Sequence[str], None] = '4c841354f311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_resumes',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('storage_bucket', sa.String(length=100), nullable=False),
    sa.Column('storage_object_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidate_resumes_owner_created', 'candidate_resumes', ['owner_user_id', 'created_at'], unique=False)
    op.create_index('uq_candidate_resumes_owner_default', 'candidate_resumes', ['owner_user_id'], unique=True, postgresql_where=sa.text('is_default = true'))
    op.add_column('applications', sa.Column('candidate_resume_id', sa.UUID(), nullable=True))
    op.create_index('idx_applications_candidate_resume', 'applications', ['candidate_resume_id'], unique=False)
    op.create_foreign_key(
        'fk_applications_candidate_resume_id',
        'applications',
        'candidate_resumes',
        ['candidate_resume_id'],
        ['id'],
        ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_applications_candidate_resume_id', 'applications', type_='foreignkey')
    op.drop_index('idx_applications_candidate_resume', table_name='applications')
    op.drop_column('applications', 'candidate_resume_id')
    op.drop_index('uq_candidate_resumes_owner_default', table_name='candidate_resumes', postgresql_where=sa.text('is_default = true'))
    op.drop_index('idx_candidate_resumes_owner_created', table_name='candidate_resumes')
    op.drop_table('candidate_resumes')
    # ### end Alembic commands ###
